# Generated by Django 4.2.11 on 2024-03-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(choices=[("m", "Male"), ("f", "Female")], default="m", max_length=1),
        ),
    ]
